### ISSUE TITLE
API Call returning website html rather than json

### ISSUE THREAD

**Issue by bmazerolle** [samuel-pratt/ferrytimes-api#8]
Hi Sam,

This is an awesome project, thanks a bunch for doing this. 

I am pretty new to working with APIs so I am hoping I'm just making a stupid mistake in my request. I'm working in React with a basic fetch() call:

`fetch("https://ferrytimes.ca/api/tsawwassen", {
                method: 'GET',
		headers: {
			'Accept': 'application/json',
			'Content-Type': 'application/json',
		}})
		.then(function(response) {
			return response.text();
		}).then(function(data) {
			console.log(data); 
		})
		.catch(error => console.log('Authorization failed : ' + error.message));`
		
This returns the source html of your home page itself rather than the json data I was looking for. I tried using `response.json()` but get a "Unexpected token < in JSON at position 0" error which indicates to me I'm not receiving the json response. I also tried using postman to the same effect so I assume I am just looking at the wrong api link.

Any help is appreciated, thanks again and I look forward to being able to contribute to your project in the near future.

**Comment by samuel-pratt** [comment]
Hi Ben,

I'm seeing the same error, I don't think it's a mistake on your end. 

The issue seems to be that the app thinks it's receiving a request to the home page. This is the output on the Heroku console: 
`2021-02-20T19:18:49.491101+00:00 heroku[router]: at=info method=GET path="/" host=www.ferrytimes.ca request_id=747090c3-10bf-4670-a10b-c7f93505504d fwd="96.54.46.229" dyno=web.1 connect=1ms service=4ms status=200 bytes=3963 protocol=http`
`2021-02-20T19:18:49.490237+00:00 app[web.1]: 10.47.227.158 - - [20/Feb/2021:19:18:49 +0000] "GET / HTTP/1.1" 200 3769 "https://ferrytimes.ca/api/" "PostmanRuntime/7.26.8"`

I'll start on this today, but I'm not sure what the issue could be. It works when running locally though, so if this is a blocker for your project you could run the api locally until this is fixed.

**Comment by samuel-pratt** [comment]
Not sure the cause for it, but when sending requests in postman add www to the start of the url, it should work then.

It looks like this isn't an issue with the code but with the domain name setup, so I'll update the readme for now and see what can be done.
